### ISSUE TITLE
Implement Context-powered state management

### ISSUE THREAD

**Issue by conor-jh** [oslabs-beta/Interspect#53]
## User story
As a developer working on this application, I should be able to pass global state values down without the need to prop drill so that I can simplify state access in nested child components.

### Acceptance criteria
- Context API for stateful tests variable is created and exported 
- Context Provider from above context is created and exported
- Panels are wrapped in context provider
- the test and setTests variables in each file where tests or setTests will be used are available via the API
- Test-related variables from props in all files are removed
 - Data Canvas components are drilled from the panels-level.

### Research questions
- What are best practices for using React’s Context API?
- What needs to be refactored to take advantage of state management?
- Should we set internal guidelines on when to use Context vs. drill props?

**Comment by joepav** [comment]
I reexamined this and removed the "Data Tree(?)" components as props to be passed down from higher levels.  The data canvas component (which is now a prop) creates some of these trees, and the tests creation and updating logic seems better nested in the TestsPanel, and with the adjustments we've made, our prop count at every level is much more manageable 😁
